"""empty message

Revision ID: 4ba30f4818e7
Revises: 
Create Date: 2024-02-16 17:09:15.608543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba30f4818e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_name')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(length=40), nullable=True),
    sa.Column('recipe_name', sa.String(length=100), nullable=True),
    sa.Column('ingredient', sa.String(length=200), nullable=True),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('recipe_instructions', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muscle_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muscle_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('completed_routines', sa.Integer(), nullable=True),
    sa.Column('user_type', sa.String(length=40), nullable=True),
    sa.Column('singup_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('goal', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=80), nullable=False),
    sa.Column('difficulty_level', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('img_source', sa.String(length=120), nullable=True),
    sa.Column('video_source', sa.String(length=120), nullable=True),
    sa.Column('muscle_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_name', sa.String(length=40), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('final_date', sa.Date(), nullable=True),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.Column('difficulty_level', sa.String(length=40), nullable=True),
    sa.Column('type_of_routine', sa.String(length=40), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_name')
    )
    op.create_table('routines_aux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reps_by_exercise', sa.Integer(), nullable=True),
    sa.Column('num_of_series', sa.Integer(), nullable=True),
    sa.Column('assignated_day', sa.Date(), nullable=True),
    sa.Column('assignated_hour', sa.Time(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routines_aux')
    op.drop_table('routines')
    op.drop_table('exercises')
    op.drop_table('user')
    op.drop_table('muscles')
    op.drop_table('meals')
    op.drop_table('equipment')
    # ### end Alembic commands ###
