"""empty message

Revision ID: 550fd3c9d0c5
Revises: 09691d4fea80
Create Date: 2024-02-01 18:37:04.654408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550fd3c9d0c5'
down_revision = '09691d4fea80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipment_name')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal', sa.String(length=40), nullable=True),
    sa.Column('recipe_name', sa.String(length=100), nullable=True),
    sa.Column('ingredient', sa.String(length=200), nullable=True),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('fats', sa.Float(), nullable=True),
    sa.Column('proteins', sa.Float(), nullable=True),
    sa.Column('recipe_instructions', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('muscles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muscle_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muscle_name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=80), nullable=False),
    sa.Column('difficulty_level', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('img_source', sa.String(length=120), nullable=True),
    sa.Column('video_source', sa.String(length=120), nullable=True),
    sa.Column('muscle_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['muscle_id'], ['muscles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_name', sa.String(length=40), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('final_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_name')
    )
    op.create_table('routines_aux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reps_by_exercise', sa.Integer(), nullable=True),
    sa.Column('num_of_series', sa.Integer(), nullable=True),
    sa.Column('assignated_day', sa.Date(), nullable=True),
    sa.Column('assignated_hour', sa.Time(), nullable=True),
    sa.Column('routine_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_new', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('completed_routines', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('singup_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('goal', sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(None, ['user_name'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('goal')
        batch_op.drop_column('gender')
        batch_op.drop_column('height')
        batch_op.drop_column('weight')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('singup_date')
        batch_op.drop_column('user_type')
        batch_op.drop_column('completed_routines')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('is_new')
        batch_op.drop_column('user_name')

    op.drop_table('routines_aux')
    op.drop_table('routines')
    op.drop_table('exercises')
    op.drop_table('muscles')
    op.drop_table('meals')
    op.drop_table('equipment')
    # ### end Alembic commands ###
