"""empty message

Revision ID: a1aaadce04f6
Revises: 8fc7082a99b2
Create Date: 2024-02-04 17:12:23.516450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1aaadce04f6'
down_revision = '8fc7082a99b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premium', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))
        batch_op.drop_constraint('user_user_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['last_name'])
        batch_op.create_unique_constraint(None, ['first_name'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_user_name_key', ['user_name'])
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('premium')

    # ### end Alembic commands ###
