"""empty message

Revision ID: f01f69cf308c
Revises: a1aaadce04f6
Create Date: 2024-02-04 17:26:40.475253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01f69cf308c'
down_revision = 'a1aaadce04f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('type_of_routine', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routines', schema=None) as batch_op:
        batch_op.drop_column('type_of_routine')
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('picture')

    # ### end Alembic commands ###
